[package]
name = "linux-cec"
version = "0.2.0"
edition = "2021"
authors = ["Vicki Pfau <vi@endrift.com>"]
license = "LGPL-2.1-or-later"
description = "Library for userspace interactions with CEC on Linux"
repository = "https://gitlab.steamos.cloud/holo/linux-cec/"
readme = "../README.md"
keywords = ["cec"]
categories = ["api-bindings", "hardware-support"]

[features]
default = ["async", "cec-attach-tty", "cectool", "tracing"]
async = ["dep:tokio"]
cectool = ["dep:clap"]
cec-attach-tty = ["nix/term", "dep:udev"]
tracing = ["dep:tracing"]
serde = ["dep:serde"]

[lib]

[[bin]]
name = "cectool"
required-features = ["cectool"]

[[bin]]
name = "cec-attach-tty"
required-features = ["cec-attach-tty"]

[dev-dependencies]
serde_json = "1.0"

[dependencies]
bitfield-struct = "0.13"
bitflags = "2.6"
clap = { version = "4.5", default-features = false, features = ["derive", "help", "std", "usage"], optional = true }
nix = { version = "0.31", default-features = false, features = ["fs", "ioctl", "poll"] }
linux-cec-macros = { version = "0.2.0", path = "../linux-cec-macros" }
linux-cec-sys = { version = "0.1.0", path = "../linux-cec-sys" }
num_enum = "0.7"
serde = { version = "1.0", optional = true, features = ["derive"] }
strum = { version = "0.28", features = ["derive"] }
thiserror = "2.0"
tinyvec = "1.9"
tracing = { version = "0.1", default-features = false, optional = true }
tokio = { version = "1", default-features = false, features = ["fs", "macros", "rt-multi-thread", "sync"], optional = true }
udev = { version = "0.9", optional = true }
