//! # D-Bus interface proxy for: `com.steampowered.CecDaemon1.Config1`
//!
//! This code was generated by `zbus-xmlgen` `5.3.1` from D-Bus introspection data.
//! Source: `com.steampowered.CecDaemon1.Config1.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.steampowered.CecDaemon1.Config1",
    default_service = "com.steampowered.CecDaemon1",
    default_path = "/com/steampowered/CecDaemon1/Daemon"
)]
pub trait Config1 {
    /// Reload method
    fn reload(&self) -> zbus::Result<()>;

    /// AllowStandby property
    #[zbus(property)]
    fn allow_standby(&self) -> zbus::Result<bool>;

    /// InactiveSourceOnSuspend property
    #[zbus(property)]
    fn inactive_source_on_suspend(&self) -> zbus::Result<bool>;

    /// Uinput property
    #[zbus(property)]
    fn uinput(&self) -> zbus::Result<bool>;

    /// LogicalAddress property
    #[zbus(property)]
    fn logical_address(&self) -> zbus::Result<u8>;

    /// Mappings property
    #[zbus(property)]
    fn mappings(&self) -> zbus::Result<Vec<(Vec<u8>, u16)>>;

    /// OsdName property
    #[zbus(property)]
    fn osd_name(&self) -> zbus::Result<String>;

    /// RequestActiveSource property
    #[zbus(property)]
    fn request_active_source(&self) -> zbus::Result<bool>;

    /// SuspendTv property
    #[zbus(property)]
    fn suspend_tv(&self) -> zbus::Result<bool>;

    /// VendorId property
    #[zbus(property)]
    fn vendor_id(&self) -> zbus::Result<i32>;

    /// WakeTv property
    #[zbus(property)]
    fn wake_tv(&self) -> zbus::Result<bool>;
}
